### ISSUE TITLE
1248 Every derived table must have its own alias

### ISSUE THREAD

**Issue by igormukhingmailcom** [portphp/dbal#4]
Hi, guys.

Have next issue. Typical `DbalReader` config:

```
# services.yml
services:
    app.reader:
        class: Port\Dbal\DbalReader
        arguments:
            - "@doctrine.dbal.import_connection"
            - "SELECT * FROM category AS c"
```

Running that reader cause next error:

```bash
In AbstractMySQLDriver.php line 121:
                                                                                                       
  An exception occurred while executing 'SELECT COUNT(*) FROM (SELECT * FROM category AS c)':          
                                                                                                       
  SQLSTATE[42000]: Syntax error or access violation: 1248 Every derived table must have its own alias
```

Fix:

```
# src/DbalReader.php
    ...
    private function doCalcRowCount()
    {
        $statement = $this->prepare(sprintf('SELECT COUNT(*) FROM (%s) AS __portPhp_DbalReader_doCalcRowCount', $this->sql), $this->params); # <------------ HERE
        $statement->execute();

        $this->rowCount = (int) $statement->fetchColumn(0);
    }
    ...
```

I'm not sure about unique naming (named as `__portPhp_DbalReader_doCalcRowCount` in nexample), so not performing pull-request...

Could you please add that fix? Or if you're OK with naming - I will perform PR.
Thanks
